### ISSUE TITLE
Chia sẻ dataset OAI

### ISSUE THREAD

**Issue by linhduongtuan** [MIPT-Oulu/semixup#2]
Kính chào Hoàng,
Tình cờ qua Phong Ha Nguyễn mình biết tới bạn mới publish bài này. Trước đó, qua Facebook mình có đôi lần trao đổi với Trần Khánh Thượng nữa. Rất vui khi các bạn đã cùng làm việc chung chuyên ngành với nhau tại Oulu Uni. Hiện mình cũng đang theo đuổi chủ đề chẩn đoán ảnh y sinh, một bài rất tốt về COVID-19 chestXray và 1 bài đã hoàn thành thí nghiệm về COVID-19 Computated Tomography. Kết quả rất triển vọng trên cùng một model. 
Nhưng mình nghĩ chủ đề Self-, semi-, un- supervised learning vẫn là chủ đề đầy triển vọng và của tương lai như Yan LeCun đã mô tả cách đây không lâu. Và các bạn đang đóng góp cho công cuộc đó thông qua bài báo này. Mình rất thích code của bạn, rất gọn và đẹp. 
Tuy nhiên, mình có chút kinh nghiệm (thật ra tự học và làm cho vui thôi) về models (supervised learning) ~ bài toán phân loại ảnh X ray, CT, hay MRI. Vì vậy mình muốn vooc models mình đang có (rất tốt với bài toán COVID-19) với bài toán OAI của bạn. Chỉ có điều dataset gốc quá lớn do định dạng DICOM để mình có thể tải về máy đo đó mình viết issue này mong bạn chia sẻ dataset OAI này dưới dạng *jpg thì tốt quá!
Chúc cuối tuần vui vẻ
Thân ái
Linh

**Comment by hoanghng** [comment]
Cảm ơn Linh đã quan tâm repo của mình. Mình ko được có quyền phân phối lại data OAI nên rất tiếc ko thể share trực tiếp với bạn. Không có cách nào khác, bạn cần request access ở https://nda.nih.gov/oai/.
Cheers.

**Comment by linhduongtuan** [comment]
Cảm ơn Hoàng.
Linh
